[package]
name = "printr"
version = "0.1.0"
edition = "2024"

[dependencies]
anstream = "1.0.0"
anstyle = "1.0.14"
anyhow = "1.0.104"
chrono = { version = "0.4.45", features = ["serde"] }
clap = { version = "4.6.7", features = ["derive", "env"] }
escpos = { version = "0.20.0", features = ["graphics"] }
image = "0.25"
rand = "0.10.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
terminal_size = "0.4.4"
